# Generated by Django 3.2.4 on 2021-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullfilled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
