# Generated by Django 3.2.4 on 2021-07-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210709_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
